package decoder

// callsignCountries maps amateur callsign prefixes (one to four
// characters, the longest match wins) to the ISO country code ("" when
// none) and the country or entity name: the ITU allocations as tabled by
// OpenWebRX+ (owrx/lookup.py, AGPL-3.0).
var callsignCountries = map[string][2]string{
	"0S":   {"", "Principality of Seborga"},
	"1A":   {"", "Sovereign Military Order of Malta"},
	"1B":   {"", "Northern Cyprus or Blenheim Reef"},
	"1G":   {"", "Geyser Reef"},
	"1L":   {"", "Liberland"},
	"1M":   {"", "Minerva Reefs"},
	"1S":   {"", "Principality of Sealand"},
	"1Z":   {"", "Kayin State"},
	"2":    {"GB", "United Kingdom"},
	"3A":   {"MC", "Monaco"},
	"3B":   {"MU", "Mauritius"},
	"3C":   {"GQ", "Equatorial Guinea"},
	"3DA":  {"SZ", "Swaziland"},
	"3DB":  {"SZ", "Swaziland"},
	"3DC":  {"SZ", "Swaziland"},
	"3DD":  {"SZ", "Swaziland"},
	"3DE":  {"SZ", "Swaziland"},
	"3DF":  {"SZ", "Swaziland"},
	"3DG":  {"SZ", "Swaziland"},
	"3DH":  {"SZ", "Swaziland"},
	"3DI":  {"SZ", "Swaziland"},
	"3DJ":  {"SZ", "Swaziland"},
	"3DK":  {"SZ", "Swaziland"},
	"3DL":  {"SZ", "Swaziland"},
	"3DM":  {"SZ", "Swaziland"},
	"3DN":  {"FJ", "Fiji"},
	"3DO":  {"FJ", "Fiji"},
	"3DP":  {"FJ", "Fiji"},
	"3DQ":  {"FJ", "Fiji"},
	"3DR":  {"FJ", "Fiji"},
	"3DS":  {"FJ", "Fiji"},
	"3DT":  {"FJ", "Fiji"},
	"3DU":  {"FJ", "Fiji"},
	"3DV":  {"FJ", "Fiji"},
	"3DW":  {"FJ", "Fiji"},
	"3DX":  {"FJ", "Fiji"},
	"3DY":  {"FJ", "Fiji"},
	"3DZ":  {"FJ", "Fiji"},
	"3E":   {"PA", "Panama"},
	"3F":   {"PA", "Panama"},
	"3G":   {"CL", "Chile"},
	"3H":   {"CN", "China"},
	"3I":   {"CN", "China"},
	"3J":   {"CN", "China"},
	"3K":   {"CN", "China"},
	"3L":   {"CN", "China"},
	"3M":   {"CN", "China"},
	"3N":   {"CN", "China"},
	"3O":   {"CN", "China"},
	"3P":   {"CN", "China"},
	"3Q":   {"CN", "China"},
	"3R":   {"CN", "China"},
	"3S":   {"CN", "China"},
	"3T":   {"CN", "China"},
	"3U":   {"CN", "China"},
	"3V":   {"TN", "Tunisia"},
	"3W":   {"VN", "Vietnam"},
	"3X":   {"GN", "Guinea"},
	"3Y":   {"NO", "Norway"},
	"3Z":   {"PL", "Poland"},
	"4A":   {"MX", "Mexico"},
	"4B":   {"MX", "Mexico"},
	"4C":   {"MX", "Mexico"},
	"4D":   {"PH", "Philippines"},
	"4E":   {"PH", "Philippines"},
	"4F":   {"PH", "Philippines"},
	"4G":   {"PH", "Philippines"},
	"4H":   {"PH", "Philippines"},
	"4I":   {"PH", "Philippines"},
	"4J":   {"AZ", "Azerbaijan"},
	"4K":   {"AZ", "Azerbaijan"},
	"4L":   {"GE", "Georgia"},
	"4M":   {"VE", "Venezuela"},
	"4O":   {"ME", "Montenegro"},
	"4P":   {"LK", "Sri Lanka"},
	"4Q":   {"LK", "Sri Lanka"},
	"4R":   {"LK", "Sri Lanka"},
	"4S":   {"LK", "Sri Lanka"},
	"4T":   {"PE", "Peru"},
	"4U":   {"", "United Nations"},
	"4V":   {"HT", "Haiti"},
	"4W":   {"TL", "East Timor"},
	"4X":   {"IL", "Israel"},
	"4Y":   {"", "International Civil Aviation Organization"},
	"4Z":   {"IL", "Israel"},
	"5A":   {"LY", "Libya"},
	"5B":   {"CY", "Cyprus"},
	"5C":   {"MA", "Morocco"},
	"5D":   {"MA", "Morocco"},
	"5E":   {"MA", "Morocco"},
	"5F":   {"MA", "Morocco"},
	"5G":   {"MA", "Morocco"},
	"5H":   {"TZ", "Tanzania"},
	"5I":   {"TZ", "Tanzania"},
	"5J":   {"CO", "Colombia"},
	"5K":   {"CO", "Colombia"},
	"5L":   {"LR", "Liberia"},
	"5M":   {"LR", "Liberia"},
	"5N":   {"NG", "Nigeria"},
	"5O":   {"NG", "Nigeria"},
	"5P":   {"DK", "Denmark"},
	"5Q":   {"DK", "Denmark"},
	"5R":   {"MG", "Madagascar"},
	"5S":   {"MG", "Madagascar"},
	"5T":   {"MR", "Mauritania"},
	"5U":   {"NE", "Niger"},
	"5V":   {"TG", "Togo"},
	"5W":   {"WS", "Western Samoa"},
	"5X":   {"UG", "Uganda"},
	"5Y":   {"KE", "Kenya"},
	"5Z":   {"KE", "Kenya"},
	"6A":   {"EG", "Egypt"},
	"6B":   {"EG", "Egypt"},
	"6C":   {"SY", "Syria"},
	"6D":   {"MX", "Mexico"},
	"6E":   {"MX", "Mexico"},
	"6F":   {"MX", "Mexico"},
	"6G":   {"MX", "Mexico"},
	"6H":   {"MX", "Mexico"},
	"6I":   {"MX", "Mexico"},
	"6J":   {"MX", "Mexico"},
	"6K":   {"HK", "South Korea"},
	"6L":   {"HK", "South Korea"},
	"6M":   {"HK", "South Korea"},
	"6N":   {"HK", "South Korea"},
	"6O":   {"SO", "Somalia"},
	"6P":   {"PK", "Pakistan"},
	"6Q":   {"PK", "Pakistan"},
	"6R":   {"PK", "Pakistan"},
	"6S":   {"PK", "Pakistan"},
	"6T":   {"SD", "Sudan"},
	"6U":   {"SD", "Sudan"},
	"6V":   {"SN", "Senegal"},
	"6W":   {"SN", "Senegal"},
	"6X":   {"MG", "Madagascar"},
	"6Y":   {"JM", "Jamaica"},
	"6Z":   {"LR", "Liberia"},
	"7A":   {"ID", "Indonesia"},
	"7B":   {"ID", "Indonesia"},
	"7C":   {"ID", "Indonesia"},
	"7D":   {"ID", "Indonesia"},
	"7E":   {"ID", "Indonesia"},
	"7F":   {"ID", "Indonesia"},
	"7G":   {"ID", "Indonesia"},
	"7H":   {"ID", "Indonesia"},
	"7I":   {"ID", "Indonesia"},
	"7J":   {"JP", "Japan"},
	"7K":   {"JP", "Japan"},
	"7L":   {"JP", "Japan"},
	"7M":   {"JP", "Japan"},
	"7N":   {"JP", "Japan"},
	"7O":   {"YE", "Yemen"},
	"7P":   {"LS", "Lesotho"},
	"7Q":   {"MW", "Malawi"},
	"7R":   {"DZ", "Algeria"},
	"7S":   {"SE", "Sweden"},
	"7T":   {"DZ", "Algeria"},
	"7U":   {"DZ", "Algeria"},
	"7V":   {"DZ", "Algeria"},
	"7W":   {"DZ", "Algeria"},
	"7X":   {"DZ", "Algeria"},
	"7Y":   {"DZ", "Algeria"},
	"7Z":   {"SA", "Saudi Arabia"},
	"8A":   {"ID", "Indonesia"},
	"8B":   {"ID", "Indonesia"},
	"8C":   {"ID", "Indonesia"},
	"8D":   {"ID", "Indonesia"},
	"8E":   {"ID", "Indonesia"},
	"8F":   {"ID", "Indonesia"},
	"8G":   {"ID", "Indonesia"},
	"8H":   {"ID", "Indonesia"},
	"8I":   {"ID", "Indonesia"},
	"8J":   {"JP", "Japan"},
	"8K":   {"JP", "Japan"},
	"8L":   {"JP", "Japan"},
	"8M":   {"JP", "Japan"},
	"8N":   {"JP", "Japan"},
	"8O":   {"BW", "Botswana"},
	"8P":   {"BB", "Barbados"},
	"8Q":   {"MV", "Maldives"},
	"8R":   {"GY", "Guyana"},
	"8S":   {"SE", "Sweden"},
	"8T":   {"IN", "India"},
	"8U":   {"IN", "India"},
	"8V":   {"IN", "India"},
	"8W":   {"IN", "India"},
	"8X":   {"IN", "India"},
	"8Y":   {"IN", "India"},
	"8Z":   {"SA", "Saudi Arabia"},
	"9A":   {"HR", "Croatia"},
	"9B":   {"IR", "Iran"},
	"9C":   {"IR", "Iran"},
	"9D":   {"IR", "Iran"},
	"9E":   {"ET", "Ethiopia"},
	"9F":   {"ET", "Ethiopia"},
	"9G":   {"GH", "Ghana"},
	"9H":   {"MT", "Malta"},
	"9I":   {"ZM", "Zambia"},
	"9J":   {"ZM", "Zambia"},
	"9K":   {"KW", "Kuwait"},
	"9L":   {"SL", "Sierra Leone"},
	"9M":   {"MY", "Malaysia"},
	"9M0":  {"MY", "Spratly Islands"},
	"9N":   {"NP", "Nepal"},
	"9O":   {"CD", "Democratic Republic of Congo"},
	"9P":   {"CD", "Democratic Republic of Congo"},
	"9Q":   {"CD", "Democratic Republic of Congo"},
	"9R":   {"CD", "Democratic Republic of Congo"},
	"9S":   {"CD", "Democratic Republic of Congo"},
	"9T":   {"CD", "Democratic Republic of Congo"},
	"9U":   {"BI", "Burundi"},
	"9V":   {"SG", "Singapore"},
	"9W":   {"MY", "Malaysia"},
	"9X":   {"RW", "Rwanda"},
	"9Y":   {"TT", "Trinidad and Tobago"},
	"9Z":   {"TT", "Trinidad and Tobago"},
	"A2":   {"BW", "Botswana"},
	"A3":   {"TO", "Tonga"},
	"A4":   {"OM", "Oman"},
	"A5":   {"BT", "Bhutan"},
	"A6":   {"AE", "United Arab Emirates"},
	"A7":   {"QA", "Qatar"},
	"A8":   {"LR", "Liberia"},
	"A9":   {"BH", "Bahrain"},
	"AA":   {"US", "United States"},
	"AB":   {"US", "United States"},
	"AC":   {"US", "United States"},
	"AD":   {"US", "United States"},
	"AE":   {"US", "United States"},
	"AF":   {"US", "United States"},
	"AG":   {"US", "United States"},
	"AH":   {"US", "United States"},
	"AI":   {"US", "United States"},
	"AJ":   {"US", "United States"},
	"AK":   {"US", "United States"},
	"AL":   {"US", "United States"},
	"AM":   {"ES", "Spain"},
	"AN":   {"ES", "Spain"},
	"AO":   {"ES", "Spain"},
	"AP":   {"PK", "Pakistan"},
	"AQ":   {"PK", "Pakistan"},
	"AR":   {"PK", "Pakistan"},
	"AS":   {"PK", "Pakistan"},
	"AT":   {"IN", "India"},
	"AU":   {"IN", "India"},
	"AV":   {"IN", "India"},
	"AW":   {"IN", "India"},
	"AX":   {"AU", "Australia"},
	"AY":   {"AR", "Argentina"},
	"AZ":   {"AR", "Argentina"},
	"B":    {"CN", "China"},
	"BM":   {"TW", "Taiwan"},
	"BN":   {"TW", "Taiwan"},
	"BO":   {"TW", "Taiwan"},
	"BP":   {"TW", "Taiwan"},
	"BQ":   {"TW", "Taiwan"},
	"BU":   {"TW", "Taiwan"},
	"BV":   {"TW", "Taiwan"},
	"BV9":  {"TW", "Spratly Islands"},
	"BW":   {"TW", "Taiwan"},
	"BX":   {"TW", "Taiwan"},
	"C2":   {"NR", "Nauru"},
	"C3":   {"AD", "Andorra"},
	"C4":   {"CY", "Cyprus"},
	"C5":   {"GM", "Gambia"},
	"C6":   {"BS", "Bahamas"},
	"C7":   {"", "World Meteorological Organization"},
	"C8":   {"MZ", "Mozambique"},
	"C9":   {"MZ", "Mozambique"},
	"CA":   {"CL", "Chile"},
	"CB":   {"CL", "Chile"},
	"CC":   {"CL", "Chile"},
	"CD":   {"CL", "Chile"},
	"CE":   {"CL", "Chile"},
	"CF":   {"CA", "Canada"},
	"CG":   {"CA", "Canada"},
	"CH":   {"CA", "Canada"},
	"CI":   {"CA", "Canada"},
	"CJ":   {"CA", "Canada"},
	"CK":   {"CA", "Canada"},
	"CL":   {"CU", "Cuba"},
	"CM":   {"CU", "Cuba"},
	"CN":   {"MA", "Morocco"},
	"CO":   {"CU", "Cuba"},
	"CP":   {"BO", "Bolivia"},
	"CQ":   {"PT", "Portugal"},
	"CR":   {"PT", "Portugal"},
	"CS":   {"PT", "Portugal"},
	"CT":   {"PT", "Portugal"},
	"CU":   {"PT", "Portugal"},
	"CV":   {"UY", "Uruguay"},
	"CW":   {"UY", "Uruguay"},
	"CX":   {"UY", "Uruguay"},
	"CY":   {"CA", "Canada"},
	"CZ":   {"CA", "Canada"},
	"D0":   {"UA", "Donetsk"},
	"D1":   {"UA", "Donetsk"},
	"D2":   {"AO", "Angola"},
	"D3":   {"AO", "Angola"},
	"D4":   {"CV", "Cape Verde"},
	"D5":   {"LR", "Liberia"},
	"D6":   {"KM", "Comoros"},
	"D7":   {"HK", "South Korea"},
	"D8":   {"HK", "South Korea"},
	"D9":   {"HK", "South Korea"},
	"DA":   {"DE", "Germany"},
	"DB":   {"DE", "Germany"},
	"DC":   {"DE", "Germany"},
	"DD":   {"DE", "Germany"},
	"DE":   {"DE", "Germany"},
	"DF":   {"DE", "Germany"},
	"DG":   {"DE", "Germany"},
	"DH":   {"DE", "Germany"},
	"DI":   {"DE", "Germany"},
	"DJ":   {"DE", "Germany"},
	"DK":   {"DE", "Germany"},
	"DL":   {"DE", "Germany"},
	"DM":   {"DE", "Germany"},
	"DN":   {"DE", "Germany"},
	"DO":   {"DE", "Germany"},
	"DP":   {"DE", "Germany"},
	"DQ":   {"DE", "Germany"},
	"DR":   {"DE", "Germany"},
	"DS":   {"HK", "South Korea"},
	"DT":   {"HK", "South Korea"},
	"DU":   {"PH", "Philippines"},
	"DV":   {"PH", "Philippines"},
	"DW":   {"PH", "Philippines"},
	"DX":   {"PH", "Philippines"},
	"DX0":  {"PH", "Spratly Islands"},
	"DY":   {"PH", "Philippines"},
	"DZ":   {"PH", "Philippines"},
	"E2":   {"TH", "Thailand"},
	"E3":   {"ER", "Eritrea"},
	"E4":   {"PS", "Palestine"},
	"E5":   {"CK", "Cook Islands"},
	"E6":   {"NU", "Niue"},
	"E7":   {"BA", "Bosnia and Herzegovina"},
	"EA":   {"ES", "Spain"},
	"EB":   {"ES", "Spain"},
	"EC":   {"ES", "Spain"},
	"ED":   {"ES", "Spain"},
	"EE":   {"ES", "Spain"},
	"EF":   {"ES", "Spain"},
	"EG":   {"ES", "Spain"},
	"EH":   {"ES", "Spain"},
	"EI":   {"IE", "Ireland"},
	"EJ":   {"IE", "Ireland"},
	"EK":   {"AM", "Armenia"},
	"EL":   {"LR", "Liberia"},
	"EM":   {"UA", "Ukraine"},
	"EN":   {"UA", "Ukraine"},
	"EO":   {"UA", "Ukraine"},
	"EP":   {"IR", "Iran"},
	"EQ":   {"IR", "Iran"},
	"ER":   {"MD", "Moldova"},
	"ES":   {"EE", "Estonia"},
	"ET":   {"ET", "Ethiopia"},
	"EU":   {"BY", "Belarus"},
	"EV":   {"BY", "Belarus"},
	"EW":   {"BY", "Belarus"},
	"EX":   {"KG", "Kyrgyzstan"},
	"EY":   {"TJ", "Tajikistan"},
	"EZ":   {"TM", "Turkmenistan"},
	"F":    {"FR", "France"},
	"G":    {"GB", "United Kingdom"},
	"H2":   {"CY", "Cyprus"},
	"H3":   {"PA", "Panama"},
	"H4":   {"SB", "Solomon Islands"},
	"H5":   {"", "Bophuthatswana"},
	"H6":   {"NI", "Nicaragua"},
	"H7":   {"NI", "Nicaragua"},
	"H8":   {"PA", "Panama"},
	"H9":   {"PA", "Panama"},
	"HA":   {"HU", "Hungary"},
	"HB":   {"CH", "Switzerland"},
	"HB0":  {"LI", "Liechtenstein"},
	"HB3Y": {"LI", "Liechtenstein"},
	"HBL":  {"LI", "Liechtenstein"},
	"HC":   {"EC", "Ecuador"},
	"HD":   {"EC", "Ecuador"},
	"HE":   {"CH", "Switzerland"},
	"HF":   {"PL", "Poland"},
	"HG":   {"HU", "Hungary"},
	"HH":   {"HT", "Haiti"},
	"HI":   {"DO", "Dominican Republic"},
	"HJ":   {"CO", "Colombia"},
	"HK":   {"CO", "Colombia"},
	"HL":   {"HK", "South Korea"},
	"HM":   {"KP", "North Korea"},
	"HN":   {"IQ", "Iraq"},
	"HO":   {"PA", "Panama"},
	"HP":   {"PA", "Panama"},
	"HQ":   {"HN", "Honduras"},
	"HR":   {"HN", "Honduras"},
	"HS":   {"TH", "Thailand"},
	"HT":   {"NI", "Nicaragua"},
	"HU":   {"SV", "El Salvador"},
	"HV":   {"VA", "Vatican"},
	"HW":   {"FR", "France"},
	"HX":   {"FR", "France"},
	"HY":   {"FR", "France"},
	"HZ":   {"SA", "Saudi Arabia"},
	"I":    {"IT", "Italy"},
	"J2":   {"DJ", "Djibouti"},
	"J3":   {"GD", "Grenada"},
	"J4":   {"GR", "Greece"},
	"J5":   {"GW", "Guinea-Bissau"},
	"J6":   {"LC", "Saint Lucia"},
	"J7":   {"DM", "Dominica"},
	"J8":   {"VC", "Saint Vincent and Grenadines"},
	"JA":   {"JP", "Japan"},
	"JB":   {"JP", "Japan"},
	"JC":   {"JP", "Japan"},
	"JD":   {"JP", "Japan"},
	"JE":   {"JP", "Japan"},
	"JF":   {"JP", "Japan"},
	"JG":   {"JP", "Japan"},
	"JH":   {"JP", "Japan"},
	"JI":   {"JP", "Japan"},
	"JJ":   {"JP", "Japan"},
	"JK":   {"JP", "Japan"},
	"JL":   {"JP", "Japan"},
	"JM":   {"JP", "Japan"},
	"JN":   {"JP", "Japan"},
	"JO":   {"JP", "Japan"},
	"JP":   {"JP", "Japan"},
	"JQ":   {"JP", "Japan"},
	"JR":   {"JP", "Japan"},
	"JS":   {"JP", "Japan"},
	"JT":   {"MN", "Mongolia"},
	"JU":   {"MN", "Mongolia"},
	"JV":   {"MN", "Mongolia"},
	"JW":   {"NO", "Norway"},
	"JX":   {"NO", "Norway"},
	"JY":   {"JO", "Jordan"},
	"JZ":   {"ID", "Indonesia"},
	"K":    {"US", "United States"},
	"L2":   {"AR", "Argentina"},
	"L3":   {"AR", "Argentina"},
	"L4":   {"AR", "Argentina"},
	"L5":   {"AR", "Argentina"},
	"L6":   {"AR", "Argentina"},
	"L7":   {"AR", "Argentina"},
	"L8":   {"AR", "Argentina"},
	"L9":   {"AR", "Argentina"},
	"LA":   {"NO", "Norway"},
	"LB":   {"NO", "Norway"},
	"LC":   {"NO", "Norway"},
	"LD":   {"NO", "Norway"},
	"LE":   {"NO", "Norway"},
	"LF":   {"NO", "Norway"},
	"LG":   {"NO", "Norway"},
	"LH":   {"NO", "Norway"},
	"LI":   {"NO", "Norway"},
	"LJ":   {"NO", "Norway"},
	"LK":   {"NO", "Norway"},
	"LL":   {"NO", "Norway"},
	"LM":   {"NO", "Norway"},
	"LN":   {"NO", "Norway"},
	"LO":   {"AR", "Argentina"},
	"LP":   {"AR", "Argentina"},
	"LQ":   {"AR", "Argentina"},
	"LR":   {"AR", "Argentina"},
	"LS":   {"AR", "Argentina"},
	"LT":   {"AR", "Argentina"},
	"LU":   {"AR", "Argentina"},
	"LV":   {"AR", "Argentina"},
	"LW":   {"AR", "Argentina"},
	"LX":   {"LU", "Luxembourg"},
	"LY":   {"LT", "Lithuania"},
	"LZ":   {"BG", "Bulgaria"},
	"M":    {"GB", "United Kingdom"},
	"N":    {"US", "United States"},
	"O1":   {"GE", "South Ossetia"},
	"OA":   {"PE", "Peru"},
	"OB":   {"PE", "Peru"},
	"OC":   {"PE", "Peru"},
	"OD":   {"LB", "Lebanon"},
	"OE":   {"AT", "Austria"},
	"OF":   {"FI", "Finland"},
	"OG":   {"FI", "Finland"},
	"OH":   {"FI", "Finland"},
	"OI":   {"FI", "Finland"},
	"OJ":   {"FI", "Finland"},
	"OK":   {"CZ", "Czech Republic"},
	"OL":   {"CZ", "Czech Republic"},
	"OM":   {"SK", "Slovakia"},
	"ON":   {"BE", "Belgium"},
	"OO":   {"BE", "Belgium"},
	"OP":   {"BE", "Belgium"},
	"OQ":   {"BE", "Belgium"},
	"OR":   {"BE", "Belgium"},
	"OS":   {"BE", "Belgium"},
	"OT":   {"BE", "Belgium"},
	"OU":   {"DK", "Denmark"},
	"OV":   {"DK", "Denmark"},
	"OW":   {"DK", "Denmark"},
	"OX":   {"DK", "Denmark"},
	"OY":   {"DK", "Denmark"},
	"OZ":   {"DK", "Denmark"},
	"P2":   {"PG", "Papua New Guinea"},
	"P3":   {"CY", "Cyprus"},
	"P4":   {"AW", "Aruba"},
	"P5":   {"KP", "North Korea"},
	"P6":   {"KP", "North Korea"},
	"P7":   {"KP", "North Korea"},
	"P8":   {"KP", "North Korea"},
	"P9":   {"KP", "North Korea"},
	"PA":   {"NL", "Netherlands"},
	"PB":   {"NL", "Netherlands"},
	"PC":   {"NL", "Netherlands"},
	"PD":   {"NL", "Netherlands"},
	"PE":   {"NL", "Netherlands"},
	"PF":   {"NL", "Netherlands"},
	"PG":   {"NL", "Netherlands"},
	"PH":   {"NL", "Netherlands"},
	"PI":   {"NL", "Netherlands"},
	"PJ":   {"AN", "Antilles (Netherlands)"},
	"PK":   {"ID", "Indonesia"},
	"PL":   {"ID", "Indonesia"},
	"PM":   {"ID", "Indonesia"},
	"PN":   {"ID", "Indonesia"},
	"PO":   {"ID", "Indonesia"},
	"PP":   {"BR", "Brazil"},
	"PQ":   {"BR", "Brazil"},
	"PR":   {"BR", "Brazil"},
	"PS":   {"BR", "Brazil"},
	"PT":   {"BR", "Brazil"},
	"PU":   {"BR", "Brazil"},
	"PV":   {"BR", "Brazil"},
	"PW":   {"BR", "Brazil"},
	"PX":   {"BR", "Brazil"},
	"PY":   {"BR", "Brazil"},
	"PZ":   {"SR", "Suriname"},
	"R":    {"RU", "Russia"},
	"RA6":  {"RU", "Chechnya"},
	"S0":   {"EH", "Western Sahara"},
	"S2":   {"BD", "Bangladesh"},
	"S3":   {"BD", "Bangladesh"},
	"S5":   {"SI", "Slovenia"},
	"S6":   {"SG", "Singapore"},
	"S7":   {"SC", "Seychelles"},
	"S8":   {"ZA", "South Africa"},
	"S9":   {"ST", "Sao Tome and Principe"},
	"SA":   {"SE", "Sweden"},
	"SB":   {"SE", "Sweden"},
	"SC":   {"SE", "Sweden"},
	"SD":   {"SE", "Sweden"},
	"SE":   {"SE", "Sweden"},
	"SF":   {"SE", "Sweden"},
	"SG":   {"SE", "Sweden"},
	"SH":   {"SE", "Sweden"},
	"SI":   {"SE", "Sweden"},
	"SJ":   {"SE", "Sweden"},
	"SK":   {"SE", "Sweden"},
	"SL":   {"SE", "Sweden"},
	"SM":   {"SE", "Sweden"},
	"SN":   {"PL", "Poland"},
	"SO":   {"PL", "Poland"},
	"SP":   {"PL", "Poland"},
	"SQ":   {"PL", "Poland"},
	"SR":   {"PL", "Poland"},
	"SS":   {"SD", "Sudan"},
	"SSA":  {"EG", "Egypt"},
	"SSB":  {"EG", "Egypt"},
	"SSC":  {"EG", "Egypt"},
	"SSD":  {"EG", "Egypt"},
	"SSE":  {"EG", "Egypt"},
	"SSF":  {"EG", "Egypt"},
	"SSG":  {"EG", "Egypt"},
	"SSH":  {"EG", "Egypt"},
	"SSI":  {"EG", "Egypt"},
	"SSJ":  {"EG", "Egypt"},
	"SSK":  {"EG", "Egypt"},
	"SSL":  {"EG", "Egypt"},
	"SSM":  {"EG", "Egypt"},
	"ST":   {"SD", "Sudan"},
	"SU":   {"EG", "Egypt"},
	"SV":   {"GR", "Greece"},
	"SW":   {"GR", "Greece"},
	"SX":   {"GR", "Greece"},
	"SY":   {"GR", "Greece"},
	"SZ":   {"GR", "Greece"},
	"T0":   {"", "Principality of Seborga"},
	"T1":   {"MD", "Transnistria"},
	"T2":   {"TV", "Tuvalu"},
	"T3":   {"KI", "Kiribati"},
	"T4":   {"CU", "Cuba"},
	"T5":   {"SO", "Somalia"},
	"T6":   {"AF", "Afghanistan"},
	"T7":   {"SM", "San Marino"},
	"T8":   {"PW", "Palau"},
	"TA":   {"TR", "Turkey"},
	"TB":   {"TR", "Turkey"},
	"TC":   {"TR", "Turkey"},
	"TD":   {"GT", "Guatemala"},
	"TE":   {"CR", "Costa Rica"},
	"TF":   {"IS", "Iceland"},
	"TG":   {"GT", "Guatemala"},
	"TH":   {"FR", "France"},
	"TI":   {"CR", "Costa Rica"},
	"TJ":   {"CM", "Cameroon"},
	"TK":   {"FR", "France"},
	"TL":   {"CF", "Central African Republic"},
	"TM":   {"FR", "France"},
	"TN":   {"CG", "Republic of Congo"},
	"TO":   {"FR", "France"},
	"TP":   {"FR", "France"},
	"TQ":   {"FR", "France"},
	"TR":   {"GA", "Gabon"},
	"TS":   {"TN", "Tunisia"},
	"TT":   {"TD", "Chad"},
	"TU":   {"CI", "Ivory Coast"},
	"TV":   {"FR", "France"},
	"TW":   {"FR", "France"},
	"TX":   {"FR", "France"},
	"TY":   {"BJ", "Benin"},
	"TZ":   {"ML", "Mali"},
	"UA":   {"RU", "Russia"},
	"UB":   {"RU", "Russia"},
	"UC":   {"RU", "Russia"},
	"UD":   {"RU", "Russia"},
	"UE":   {"RU", "Russia"},
	"UF":   {"RU", "Russia"},
	"UG":   {"RU", "Russia"},
	"UH":   {"RU", "Russia"},
	"UI":   {"RU", "Russia"},
	"UJ":   {"UZ", "Uzbekistan"},
	"UK":   {"UZ", "Uzbekistan"},
	"UL":   {"UZ", "Uzbekistan"},
	"UM":   {"UZ", "Uzbekistan"},
	"UN":   {"KZ", "Kazakhstan"},
	"UO":   {"KZ", "Kazakhstan"},
	"UP":   {"KZ", "Kazakhstan"},
	"UQ":   {"KZ", "Kazakhstan"},
	"UR":   {"UA", "Ukraine"},
	"US":   {"UA", "Ukraine"},
	"UT":   {"UA", "Ukraine"},
	"UU":   {"UA", "Ukraine"},
	"UV":   {"UA", "Ukraine"},
	"UW":   {"UA", "Ukraine"},
	"UX":   {"UA", "Ukraine"},
	"UY":   {"UA", "Ukraine"},
	"UZ":   {"UA", "Ukraine"},
	"V2":   {"AG", "Antigua and Barbuda"},
	"V3":   {"BZ", "Belize"},
	"V4":   {"KN", "Saint Kitts and Nevis"},
	"V5":   {"NA", "Namibia"},
	"V6":   {"FM", "Micronesia"},
	"V7":   {"MH", "Marshall Islands"},
	"V8":   {"BN", "Brunei"},
	"VA":   {"CA", "Canada"},
	"VB":   {"CA", "Canada"},
	"VC":   {"CA", "Canada"},
	"VD":   {"CA", "Canada"},
	"VE":   {"CA", "Canada"},
	"VF":   {"CA", "Canada"},
	"VG":   {"CA", "Canada"},
	"VH":   {"AU", "Australia"},
	"VI":   {"AU", "Australia"},
	"VJ":   {"AU", "Australia"},
	"VK":   {"AU", "Australia"},
	"VL":   {"AU", "Australia"},
	"VM":   {"AU", "Australia"},
	"VN":   {"AU", "Australia"},
	"VO":   {"CA", "Newfoundland (Canada)"},
	"VP":   {"GB", "United Kingdom"},
	"VQ":   {"GB", "United Kingdom"},
	"VR":   {"HK", "Hong Kong"},
	"VS":   {"GB", "United Kingdom"},
	"VT":   {"IN", "India"},
	"VU":   {"IN", "India"},
	"VV":   {"IN", "India"},
	"VW":   {"IN", "India"},
	"VX":   {"CA", "Canada"},
	"VY":   {"CA", "Canada"},
	"VZ":   {"AU", "Australia"},
	"W":    {"US", "United States"},
	"XA":   {"MX", "Mexico"},
	"XB":   {"MX", "Mexico"},
	"XC":   {"MX", "Mexico"},
	"XD":   {"MX", "Mexico"},
	"XE":   {"MX", "Mexico"},
	"XF":   {"MX", "Mexico"},
	"XG":   {"MX", "Mexico"},
	"XH":   {"MX", "Mexico"},
	"XI":   {"MX", "Mexico"},
	"XJ":   {"CA", "Canada"},
	"XK":   {"CA", "Canada"},
	"XL":   {"CA", "Canada"},
	"XM":   {"CA", "Canada"},
	"XN":   {"CA", "Canada"},
	"XO":   {"CA", "Canada"},
	"XP":   {"DK", "Denmark"},
	"XQ":   {"CL", "Chile"},
	"XR":   {"CL", "Chile"},
	"XS":   {"CN", "China"},
	"XT":   {"BF", "Burkina Faso"},
	"XU":   {"KH", "Cambodia"},
	"XV":   {"VN", "Vietnam"},
	"XW":   {"LA", "Laos"},
	"XX":   {"MO", "Macao"},
	"XY":   {"MM", "Myanmar"},
	"XZ":   {"MM", "Myanmar"},
	"Y2":   {"DE", "Germany"},
	"Y3":   {"DE", "Germany"},
	"Y4":   {"DE", "Germany"},
	"Y5":   {"DE", "Germany"},
	"Y6":   {"DE", "Germany"},
	"Y7":   {"DE", "Germany"},
	"Y8":   {"DE", "Germany"},
	"Y9":   {"DE", "Germany"},
	"YA":   {"AF", "Afghanistan"},
	"YB":   {"ID", "Indonesia"},
	"YC":   {"ID", "Indonesia"},
	"YD":   {"ID", "Indonesia"},
	"YE":   {"ID", "Indonesia"},
	"YF":   {"ID", "Indonesia"},
	"YG":   {"ID", "Indonesia"},
	"YH":   {"ID", "Indonesia"},
	"YI":   {"IQ", "Iraq"},
	"YJ":   {"VU", "Vanuatu"},
	"YK":   {"SY", "Syria"},
	"YL":   {"LV", "Latvia"},
	"YM":   {"TR", "Turkey"},
	"YN":   {"NI", "Nicaragua"},
	"YO":   {"RO", "Romania"},
	"YP":   {"RO", "Romania"},
	"YQ":   {"RO", "Romania"},
	"YR":   {"RO", "Romania"},
	"YS":   {"SV", "El Salvador"},
	"YT":   {"RS", "Serbia"},
	"YU":   {"RS", "Serbia"},
	"YV":   {"VE", "Venezuela"},
	"YW":   {"VE", "Venezuela"},
	"YX":   {"VE", "Venezuela"},
	"YY":   {"VE", "Venezuela"},
	"Z2":   {"ZW", "Zimbabwe"},
	"Z3":   {"MK", "Macedonia"},
	"Z6":   {"XK", "Kosovo"},
	"Z8":   {"SS", "South Sudan"},
	"ZA":   {"AL", "Albania"},
	"ZB":   {"GB", "United Kingdom"},
	"ZC":   {"GB", "United Kingdom"},
	"ZD":   {"GB", "United Kingdom"},
	"ZE":   {"GB", "United Kingdom"},
	"ZF":   {"GB", "United Kingdom"},
	"ZG":   {"GB", "United Kingdom"},
	"ZH":   {"GB", "United Kingdom"},
	"ZI":   {"GB", "United Kingdom"},
	"ZJ":   {"GB", "United Kingdom"},
	"ZK":   {"NZ", "New Zealand"},
	"ZL":   {"NZ", "New Zealand"},
	"ZM":   {"NZ", "New Zealand"},
	"ZN":   {"GB", "United Kingdom"},
	"ZO":   {"GB", "United Kingdom"},
	"ZP":   {"PY", "Paraguay"},
	"ZQ":   {"GB", "United Kingdom"},
	"ZR":   {"ZA", "South Africa"},
	"ZS":   {"ZA", "South Africa"},
	"ZT":   {"ZA", "South Africa"},
	"ZU":   {"ZA", "South Africa"},
	"ZV":   {"BR", "Brazil"},
	"ZW":   {"BR", "Brazil"},
	"ZX":   {"BR", "Brazil"},
	"ZY":   {"BR", "Brazil"},
	"ZZ":   {"BR", "Brazil"},
}
