*

!cmd/
!internal/
!go.mod
!go.sum
!.infra/docker/prod/

**/*_templ.go
**/*.gen.go
internal/db/sqlite/sqlc/
internal/http/api/openapi.json
internal/web/static/css/app.css

**/*.db
**/*.db-*
**/*.sqlite
**/*.sqlite-*
**/*.sqlite3
**/*.sqlite3-*
