package api

import (
	"context"
	"encoding/hex"
	"io"
	"net/http"
	"strconv"
	"strings"

	"github.com/yohang/mesh-sdr/internal/files"
)

// FileService reads the files the nodes sent, with the caller's rights
// (internal/files Gallery).
type FileService interface {
	// Visible returns a file the caller of ctx may see, or
	// files.ErrFileNotFound.
	Visible(ctx context.Context, id string) (files.Entry, error)
	// WriteContent writes the content of a file Visible returned.
	WriteContent(ctx context.Context, e files.Entry, w io.Writer) error
	Thumbnail(ctx context.Context, e files.Entry) ([]byte, error)
}

// FileHandlers serve GET /files/{id}/content (FIL-002) and
// GET /files/{id}/thumbnail (FIL-001), which the Files pages link to.
type FileHandlers struct {
	files FileService
}

// NewFileHandlers returns the handlers.
func NewFileHandlers(f FileService) FileHandlers { return FileHandlers{files: f} }

// GetFileContent implements StrictServerInterface.
func (h FileHandlers) GetFileContent(ctx context.Context, req GetFileContentRequestObject) (GetFileContentResponseObject, error) {
	e, err := h.files.Visible(ctx, req.Id)
	if err != nil {
		return nil, err
	}

	etag := strconv.Quote(hex.EncodeToString(e.SHA256))
	res := fileResponse{etag: etag, mime: string(e.MIME), name: e.Name, disposition: "attachment", size: e.Size}

	if req.Params.IfNoneMatch != nil && *req.Params.IfNoneMatch == etag {
		res.notModified = true

		return res, nil
	}

	// The content is streamed one stored chunk at a time.
	res.stream = func(w io.Writer) error { return h.files.WriteContent(ctx, e, w) }

	return res, nil
}

// GetFileThumbnail implements StrictServerInterface.
func (h FileHandlers) GetFileThumbnail(ctx context.Context, req GetFileThumbnailRequestObject) (GetFileThumbnailResponseObject, error) {
	e, err := h.files.Visible(ctx, req.Id)
	if err != nil {
		return nil, err
	}

	etag := strconv.Quote("t-" + hex.EncodeToString(e.SHA256))
	res := fileResponse{etag: etag, mime: string(files.MIMEJPEG)}

	if req.Params.IfNoneMatch != nil && *req.Params.IfNoneMatch == etag {
		res.notModified = true

		return res, nil
	}

	data, err := h.files.Thumbnail(ctx, e)
	if err != nil {
		return nil, err
	}

	res.size = int64(len(data))
	res.stream = func(w io.Writer) error {
		_, err := w.Write(data)

		return err
	}

	return res, nil
}

// fileResponse writes a file with its stored type (SR-30): never sniffed,
// revalidated on every use, with the name the hub generated in its
// Content-Disposition (attachment, inline or none).
type fileResponse struct {
	stream      func(w io.Writer) error
	size        int64
	etag        string
	mime        string
	name        string
	disposition string
	// public lets shared caches keep the file (receiver images); the files
	// the nodes sent are private (rights may change).
	public      bool
	notModified bool
}

func (r fileResponse) write(w http.ResponseWriter) error {
	h := w.Header()
	h.Set("ETag", r.etag)
	h.Set("Cache-Control", "private, no-cache")
	h.Set("X-Content-Type-Options", "nosniff")

	if r.public {
		h.Set("Cache-Control", "no-cache")
	}

	if r.notModified {
		w.WriteHeader(http.StatusNotModified)

		return nil
	}

	ctype := r.mime
	if strings.HasPrefix(ctype, "text/") {
		ctype += "; charset=utf-8"
	}

	h.Set("Content-Type", ctype)
	h.Set("Content-Length", strconv.FormatInt(r.size, 10))

	if r.disposition != "" {
		h.Set("Content-Disposition", r.disposition+`; filename="`+SafeFileName(r.name)+`"`)
	}

	w.WriteHeader(http.StatusOK)

	return r.stream(w)
}

func (r fileResponse) VisitGetFileContentResponse(w http.ResponseWriter) error { return r.write(w) }

func (r fileResponse) VisitGetFileThumbnailResponse(w http.ResponseWriter) error { return r.write(w) }

// SafeFileName keeps the letters, digits, dots, dashes and underscores of
// a file name (the names are generated by the hub; this is defence in
// depth for the Content-Disposition header).
func SafeFileName(name string) string {
	var b strings.Builder

	for _, c := range name {
		switch {
		case c >= 'a' && c <= 'z', c >= 'A' && c <= 'Z', c >= '0' && c <= '9', c == '.', c == '-', c == '_':
			b.WriteRune(c)
		default:
			b.WriteByte('_')
		}
	}

	s := strings.TrimLeft(b.String(), ".")
	if s == "" {
		return "file"
	}

	return s
}
