package http

import (
	"encoding/json"
	"io/fs"
	"log/slog"
	"net/http"
)

// webManifest is the web app manifest (UI-004).
type webManifest struct {
	Name            string         `json:"name"`
	ShortName       string         `json:"short_name"`
	StartURL        string         `json:"start_url"`
	Scope           string         `json:"scope"`
	Display         string         `json:"display"`
	BackgroundColor string         `json:"background_color"`
	ThemeColor      string         `json:"theme_color"`
	Icons           []manifestIcon `json:"icons"`
}

type manifestIcon struct {
	Src     string `json:"src"`
	Sizes   string `json:"sizes"`
	Type    string `json:"type"`
	Purpose string `json:"purpose,omitempty"`
}

// manifestIcons are generated by internal/web/icongen.
var manifestIcons = []manifestIcon{
	{Src: "/static/icons/icon.svg", Sizes: "any", Type: "image/svg+xml"},
	{Src: "/static/icons/icon-192.png", Sizes: "192x192", Type: "image/png"},
	{Src: "/static/icons/icon-512.png", Sizes: "512x512", Type: "image/png"},
	{Src: "/static/icons/icon-maskable-512.png", Sizes: "512x512", Type: "image/png", Purpose: "maskable"},
}

// manifest serves /manifest.webmanifest. Its colors follow the theme mode: a
// manifest has one theme color, so auto uses the light one (the document's
// media-qualified theme-color metas take precedence in browsers that
// support them).
func (m *Module) manifest(w http.ResponseWriter, r *http.Request) {
	s := m.shell.Shell(r)
	color := s.Theme.ThemeColor()

	b, err := json.Marshal(webManifest{
		Name:            s.SiteName,
		ShortName:       s.SiteName,
		StartURL:        "/",
		Scope:           "/",
		Display:         "standalone",
		BackgroundColor: color,
		ThemeColor:      color,
		Icons:           manifestIcons,
	})
	if err != nil {
		m.logger.ErrorContext(r.Context(), "encode web app manifest", slog.Any("error", err))
		m.render.Error(w, r, http.StatusInternalServerError)

		return
	}

	w.Header().Set("Content-Type", "application/manifest+json")
	w.Header().Set("Cache-Control", "no-cache")
	_, _ = w.Write(b)
}

// favicon serves /favicon.ico, which browsers request at the root.
func favicon(static fs.FS) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "image/vnd.microsoft.icon")
		http.ServeFileFS(w, r, static, "icons/favicon.ico")
	}
}
