package domain

import (
	"bytes"
	"crypto/rand"
	"encoding/binary"
	"encoding/hex"
	"fmt"
	"sync"
	"time"
)

// ErrInvalidUUID is returned for a malformed UUID.
var ErrInvalidUUID = NewError(KindInvalid, "invalid_uuid", "invalid UUID")

// maxUnixMilli is the largest timestamp a UUIDv7 holds (48 bits).
const maxUnixMilli = 1<<48 - 1

// UUID is an RFC 9562 UUID. Surrogate keys are UUIDv7 (TECHNICAL_SPEC §7.1
// "Primary keys"): time-ordered, generated by the application. The zero
// value is the nil UUID.
type UUID struct {
	b [16]byte
}

// NewUUIDv7 returns a UUIDv7 for now with random rand_a and rand_b bits
// (RFC 9562 §5.7). UUIDs created in the same millisecond are unordered among
// themselves; use a UUIDv7Generator for monotonic ids.
func NewUUIDv7(now time.Time) (UUID, error) {
	var r [2]byte
	if _, err := rand.Read(r[:]); err != nil {
		return UUID{}, fmt.Errorf("uuid: random: %w", err)
	}

	return newV7(now.UnixMilli(), binary.BigEndian.Uint16(r[:])&0x0fff)
}

// newV7 builds a UUIDv7 from a Unix millisecond timestamp and the 12-bit
// rand_a field; rand_b is random.
func newV7(ms int64, randA uint16) (UUID, error) {
	if ms < 0 || ms > maxUnixMilli {
		return UUID{}, fmt.Errorf("uuid: timestamp %d ms out of the UUIDv7 range", ms)
	}

	var u UUID
	if _, err := rand.Read(u.b[8:]); err != nil {
		return UUID{}, fmt.Errorf("uuid: random: %w", err)
	}

	// unix_ts_ms: 48 bits, big endian.
	u.b[0] = byte(ms >> 40)
	u.b[1] = byte(ms >> 32)
	u.b[2] = byte(ms >> 24)
	u.b[3] = byte(ms >> 16)
	u.b[4] = byte(ms >> 8)
	u.b[5] = byte(ms)
	// ver (0b0111) and rand_a.
	u.b[6] = 0x70 | byte(randA>>8)&0x0f
	u.b[7] = byte(randA)
	// var (0b10) and rand_b.
	u.b[8] = 0x80 | u.b[8]&0x3f

	return u, nil
}

// UUIDv7Generator creates UUIDv7 values that are strictly increasing, also
// within one millisecond and when the clock goes backwards: rand_a is a
// counter seeded randomly each millisecond (RFC 9562 §6.2 method 1). It is
// safe for concurrent use. Share one generator per process (inject it).
type UUIDv7Generator struct {
	mu     sync.Mutex
	lastMS int64
	seq    uint16
}

// NewUUIDv7Generator returns a monotonic UUIDv7 generator.
func NewUUIDv7Generator() *UUIDv7Generator { return &UUIDv7Generator{lastMS: -1} }

// New returns the next UUIDv7 for now.
func (g *UUIDv7Generator) New(now time.Time) (UUID, error) {
	g.mu.Lock()
	defer g.mu.Unlock()

	ms := now.UnixMilli()

	if ms <= g.lastMS {
		// Same millisecond, or the clock went backwards: keep the last
		// timestamp and increment the counter; on overflow, borrow the next
		// millisecond.
		ms = g.lastMS

		g.seq++
		if g.seq > 0x0fff {
			ms++

			seed, err := randomSeed()
			if err != nil {
				return UUID{}, err
			}

			g.seq = seed
		}
	} else {
		seed, err := randomSeed()
		if err != nil {
			return UUID{}, err
		}

		g.seq = seed
	}

	u, err := newV7(ms, g.seq)
	if err != nil {
		return UUID{}, err
	}

	g.lastMS = ms

	return u, nil
}

// randomSeed returns a random counter start in the lower half of the 12-bit
// range, leaving room for at least 2048 ids per millisecond.
func randomSeed() (uint16, error) {
	var r [2]byte
	if _, err := rand.Read(r[:]); err != nil {
		return 0, fmt.Errorf("uuid: random: %w", err)
	}

	return binary.BigEndian.Uint16(r[:]) & 0x07ff, nil
}

// ParseUUID parses the canonical textual form
// xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx (hex, any case).
func ParseUUID(s string) (UUID, error) {
	if len(s) != 36 || s[8] != '-' || s[13] != '-' || s[18] != '-' || s[23] != '-' {
		return UUID{}, ErrInvalidUUID.WithDetail(fmt.Sprintf("invalid UUID %q: want xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx", s))
	}

	var u UUID

	hexDigits := s[0:8] + s[9:13] + s[14:18] + s[19:23] + s[24:36]
	if _, err := hex.Decode(u.b[:], []byte(hexDigits)); err != nil {
		return UUID{}, ErrInvalidUUID.WithDetail(fmt.Sprintf("invalid UUID %q: not hexadecimal", s))
	}

	return u, nil
}

// MustParseUUID is ParseUUID that panics on error. Tests and constants only.
func MustParseUUID(s string) UUID {
	u, err := ParseUUID(s)
	if err != nil {
		panic(err)
	}

	return u
}

// UUIDFromBytes returns the UUID held in 16 bytes (for example a BLOB(16)
// column).
func UUIDFromBytes(b []byte) (UUID, error) {
	if len(b) != 16 {
		return UUID{}, ErrInvalidUUID.WithDetail(fmt.Sprintf("invalid UUID: %d bytes, want 16", len(b)))
	}

	var u UUID
	copy(u.b[:], b)

	return u, nil
}

// String returns the canonical lowercase form.
func (u UUID) String() string {
	var buf [36]byte

	hex.Encode(buf[0:8], u.b[0:4])
	buf[8] = '-'
	hex.Encode(buf[9:13], u.b[4:6])
	buf[13] = '-'
	hex.Encode(buf[14:18], u.b[6:8])
	buf[18] = '-'
	hex.Encode(buf[19:23], u.b[8:10])
	buf[23] = '-'
	hex.Encode(buf[24:36], u.b[10:16])

	return string(buf[:])
}

// Bytes returns a copy of the 16 bytes.
func (u UUID) Bytes() []byte { return bytes.Clone(u.b[:]) }

// IsZero reports whether u is the nil UUID.
func (u UUID) IsZero() bool { return u == UUID{} }

// Version returns the version field (7 for UUIDv7).
func (u UUID) Version() int { return int(u.b[6] >> 4) }

// Time returns the timestamp of a UUIDv7 (millisecond precision, UTC). It
// is meaningless for other versions.
func (u UUID) Time() time.Time {
	ms := int64(u.b[0])<<40 | int64(u.b[1])<<32 | int64(u.b[2])<<24 |
		int64(u.b[3])<<16 | int64(u.b[4])<<8 | int64(u.b[5])

	return time.UnixMilli(ms).UTC()
}

// Compare returns -1, 0 or +1 by byte order, which is creation order for
// UUIDv7.
func (u UUID) Compare(other UUID) int { return bytes.Compare(u.b[:], other.b[:]) }
